#!/bin/sh

# Supermagical script to install all the needed dependencies
# for mongrel2 and all the needed lua libs

sudo apt-get install -y build-essential git-core lua5.1 liblua5.1-0-dev uuid-dev liblua5.1-lpeg-dev liblua5.1-socket-dev libsqlite3-dev sqlite3 libssl-dev

mkdir dist
cd dist

# zeromq
ZEROMQ=zeromq-2.1.11
wget http://download.zeromq.org/${ZEROMQ}.tar.gz
tar xzvf ${ZEROMQ}.tar.gz
cd ${ZEROMQ}/
./configure
make
sudo make install
sudo ldconfig
cd ..

# redis
wget http://redis.googlecode.com/files/redis-2.0.4.tar.gz
tar xzvf redis-2.0.4.tar.gz
cd redis-2.0.4/
make
sudo make install
cd ..

# mongrel2
git clone https://github.com/zedshaw/mongrel2
make
sudo make install
cd ..

# lua stuff

mkdir lua
cd lua


git clone git://github.com/harningt/luajson.git
cd luajson
make
sudo make install
cd ..

git clone git://github.com/iamaleksey/lua-zmq.git
cd lua-zmq
make
sudo make install
cd ..

git clone git://github.com/jsimmons/mongrel2-lua.git
cd mongrel2-lua
sudo make
cd ..

# git clone git@github.com:ayourtch/gliese.git
git clone git://github.com/ayourtch/gliese.git

cd ..
# now in dist

